### ISSUE TITLE
Preferences, uninstall

### ISSUE THREAD

**Issue by chrismurrph** [Misophistful/borealis-cursive-theme#1]
It is not obvious to me where 'Preferences' are (for enabling the rainbow colours for parens). Also it has made my text larger than it was before. How do I uninstall? There are instructions for installing but none for uninstalling, or at least de-activating. Thanks

**Comment by chrismurrph** [comment]
I deleted the jar file, then deleted what was in here:
C:\Users\Chris.IdeaIC14\config\colors
Then needed to set back to what was before, which I did by:
The correct place to change the editor appearance is through File->Settings->Editor->Colors &Fonts

**Comment by Misophistful** [comment]
Thanks for the feedback. I've added instructions to the readme, explaining how to revert and uninstall the theme.
