### ISSUE TITLE
Theme causes to break .MD files

### ISSUE THREAD

**Issue by sveri** [Misophistful/borealis-cursive-theme#2]
Hi,

After installing your awesome theme the .MD files are broken for me. Everything with spaces in front gets a white layer upon it, making the text unreadable:

![bildschirmfoto](https://cloud.githubusercontent.com/assets/498370/14402688/337746b4-fe3d-11e5-9fa4-db3f445a56f4.png)

When I select the text it looks like it should:

![bildschirmfoto-1](https://cloud.githubusercontent.com/assets/498370/14402692/49bdeb3a-fe3d-11e5-9801-c0ba5f5fb22b.png)

Is it possible to fix that?

**Comment by Misophistful** [comment]
I can't seem to recreate this issue with the current version. Could you download and reinstall the latest `Borealis.jar` and see if this issue is fixed on your end too?
